# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cdate', models.DateField()),
                ('cgirl_num', models.IntegerField()),
                ('cboy_num', models.IntegerField()),
                ('is_delete', models.BooleanField()),
            ],
            options={
                'db_table': 'class',
                'ordering': ['cname'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField()),
                ('scomment', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField()),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Class')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
        ),
    ]
